###############################
#### LOCAL PROPERTIES      ####
###############################
server:
  port: 8080

# Logging Level
logging:
  level:
    com.hashmap27: debug

# Spring 관련
spring:
  multi-datasource:
    readonly:
      jdbc-url: "jdbc:postgresql://localhost:5432/postgres"
      username: postgres
      password: 1q2w3e4r
      pool-name: hikari-cp
      maximum-pool-size: 10
      minimum-idle: 2
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    readwrite:
      jdbc-url: "jdbc:postgresql://localhost:5432/postgres"
      username: postgres
      password: 1q2w3e4r
      pool-name: hikari-cp
      maximum-pool-size: 10
      minimum-idle: 2
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true